"""S8B-T1 Add Quiz and Question models

Revision ID: 48d32c8e65ec
Revises: c2f9b7e4a1d3
Create Date: 2026-05-07 03:04:24.251769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d32c8e65ec'
down_revision: Union[str, Sequence[str], None] = 'c2f9b7e4a1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'OPEN_ENDED', name='questiontype'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('competency_areas', sa.JSON(), nullable=False),
    sa.Column('bloom_level', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('safety_category', sa.String(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('correct_option', sa.String(), nullable=True),
    sa.Column('instructor_explanation', sa.Text(), nullable=True),
    sa.Column('rubric_guide', sa.Text(), nullable=True),
    sa.Column('model_answer_outline', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=True)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('question_case_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('mapping_type', sa.Enum('THEORY_SUPPORT', 'CASE_REINFORCEMENT', 'ASSESSMENT_LINK', name='mappingtype'), nullable=False),
    sa.Column('review_status', sa.Enum('APPROVED', 'BLOCKED_REVIEW_NEEDED', 'UNMAPPED', name='reviewstatus'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_case_mappings_case_id'), 'question_case_mappings', ['case_id'], unique=False)
    op.create_index(op.f('ix_question_case_mappings_id'), 'question_case_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_question_case_mappings_question_id'), 'question_case_mappings', ['question_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('student_response_text', sa.Text(), nullable=False),
    sa.Column('auto_score', sa.Integer(), nullable=True),
    sa.Column('instructor_score', sa.Integer(), nullable=True),
    sa.Column('instructor_feedback', sa.Text(), nullable=True),
    sa.Column('grading_status', sa.Enum('PENDING', 'GRADED', 'PUBLISHED', name='gradingstatus'), nullable=False),
    sa.Column('graded_by_id', sa.String(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_answers_attempt_id'), 'quiz_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_id'), 'quiz_answers', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_question_id'), 'quiz_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answers_question_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_attempt_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_question_case_mappings_question_id'), table_name='question_case_mappings')
    op.drop_index(op.f('ix_question_case_mappings_id'), table_name='question_case_mappings')
    op.drop_index(op.f('ix_question_case_mappings_case_id'), table_name='question_case_mappings')
    op.drop_table('question_case_mappings')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
